
export const ADD_REPOSITORY = 'ADD_REPOSITORY';
export const DEL_REPOSITORY = 'DEL_REPOSITORY';
export const GET_REPOSITORY = 'GET_REPOSITORY';
export const GET_REPOSITORY_RESULT = 'GET_REPOSITORY_RESULT';