export const SHOW_MODAL_POPUP = 'SHOW_MODAL_POPUP';
export const HIDE_MODAL_POPUP = 'HIDE_MODAL_POPUP';

export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const HIDE_PROGRESS = 'HIDE_PROGRESS';

export const CHANGE_TAB = 'CHANGE_TAB';